# Generated by Django 5.1.6 on 2025-04-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balloon',
            name='balloon_type',
            field=models.CharField(choices=[('HOT_AIR', 'Hot Air Balloon'), ('GAS', 'Gas Balloon'), ('HYBRID', 'Hybrid Balloon')], default='HOT_AIR', max_length=20),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='rank',
            field=models.CharField(choices=[('CAPTAIN', 'Captain'), ('FIRST_OFFICER', 'First Officer'), ('SECOND_OFFICER', 'Second Officer')], default=('CAPTAIN', 'Captain'), max_length=20),
        ),
    ]
